name: zenbreak
description: Pausas de respiração guiada para alunos.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.4
  flutter_markdown: ^0.6.10
  dots_indicator: ^2.0.0
  supabase_flutter: ^1.4.0
  flutter_dotenv: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/policies/privacy_v1.md
    - assets/policies/terms_v1.md
    - .env
